[project]
name = "tfin"
version = "0.1.2-dev"
description = "An event driven business and financial simulator"
authors = [{name="Tim van Boxtel", email="tim@vanboxtel.ca"}]
license = "MIT"
requires-python = ">=3.14"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.1"
pytest-cov = "^7.0.0"
pyyaml = "!=6.0.0,!=5.4.0,!=5.4.1" # pyyaml is broken with cython 3
mypy = "^1.18.1"
bandit = "^1.8.6"

[build-system]
requires = ["poetry-core>=2.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ["tfin"]

[tool.coverage.report]
show_missing = true

[tool.mypy]
files=["tfin"]
check_untyped_defs = true